//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorChatBot.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculatorChatBot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCardTitleText {
            get {
                return ResourceManager.GetString("ErrorCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input: {0}.
        /// </summary>
        internal static string InputLineText {
            get {
                return ResourceManager.GetString("InputLineText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation: {0}.
        /// </summary>
        internal static string OperationTypeText {
            get {
                return ResourceManager.GetString("OperationTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        internal static string OutputResultTypeText {
            get {
                return ResourceManager.GetString("OutputResultTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string ResultsCardTitleText {
            get {
                return ResourceManager.GetString("ResultsCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a bot that can *possibly* do your math homework! Well, not all of it - not all the hard calculus problems, or the hard trigonometry problems either....
        /// </summary>
        internal static string WelcomeTeamCardIntroPart1 {
            get {
                return ResourceManager.GetString("WelcomeTeamCardIntroPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the categories of operations I can do: arithmetic, some geometric, and a few statistic operations. You ask me anything about calculus - my 🧠 will not work!.
        /// </summary>
        internal static string WelcomeTeamCardIntroPart2 {
            get {
                return ResourceManager.GetString("WelcomeTeamCardIntroPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there! 👋.
        /// </summary>
        internal static string WelcomeTeamCardTitleText {
            get {
                return ResourceManager.GetString("WelcomeTeamCardTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am a bot that can *possibly* do your math homework! Well, not all of it - not all the hard calculus problems, or the hard trigonometry problems either....
        /// </summary>
        internal static string WelcomeUserCardIntroPart1 {
            get {
                return ResourceManager.GetString("WelcomeUserCardIntroPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the categories of operations I can do: arithmetic, some geometric, and a few statistic operations. You ask me anything about calculus - my 🧠 will not work!.
        /// </summary>
        internal static string WelcomeUserCardIntroPart2 {
            get {
                return ResourceManager.GetString("WelcomeUserCardIntroPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello there! 👋.
        /// </summary>
        internal static string WelcomeUserCardTitleText {
            get {
                return ResourceManager.GetString("WelcomeUserCardTitleText", resourceCulture);
            }
        }
    }
}
